version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: my_nginx_server
    ports:
      - "8080:80"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: my_redis_db
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge